version: '2' # required to adjust maintainability checks

plugins:
  checkstyle:
    enabled: true
    config:
      file: '.checkstyle.xml'

checks:
  # We disable all the following CodeClimate checks: Checkstyle already checks for these things and has the advantage
  # that the Checkstyle config can also be used in one's IDE.
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  # Enable identical code as it's not available in Checkstyle
  identical-code:
    enabled: true

exclude_patterns:
  # Don't check test classes
  - 'injector/src/test/java/**'
  - 'injector-extras/src/test/java/**'
  - 'test-module/**'